import { env } from '@/lib/config/env';

export const DATABASE_URL = env.DATABASE_URL;
export const REDIS_URL = env.REDIS_URL;

export const JWT_ACCESS_SECRET = env.JWT_ACCESS_SECRET;
export const JWT_REFRESH_SECRET = env.JWT_REFRESH_SECRET;
export const DATABASE_ENCRYPTION_KEY = env.DATABASE_ENCRYPTION_KEY;

export const CAMPUS_API_URL = env.CAMPUS_API_URL;
export const CAMPUS_INTEGRATION_API_KEY = env.CAMPUS_INTEGRATION_API_KEY;

export const KPI_APP_SECRET = env.KPI_APP_SECRET;
export const TRUSTED_PROXY_COUNT = env.TRUSTED_PROXY_COUNT;
export const NODE_ENV = env.NODE_ENV;
export const CRON_SECRET = env.CRON_SECRET;
export const APP_VERSION = env.APP_VERSION;

export const PROTOCOL_GENERATOR_URL = env.PROTOCOL_GENERATOR_URL;
export const PROTOCOL_TEMPLATE_ID = env.PROTOCOL_TEMPLATE_ID;

export const MINIO_ENDPOINT = env.MINIO_ENDPOINT;
export const MINIO_PORT = env.MINIO_PORT;
export const MINIO_USE_SSL = env.MINIO_USE_SSL;
export const MINIO_ACCESS_KEY = env.MINIO_ACCESS_KEY;
export const MINIO_SECRET_KEY = env.MINIO_SECRET_KEY;
export const MINIO_PUBLIC_BUCKET = env.MINIO_PUBLIC_BUCKET;
export const MINIO_PUBLIC_URL_BASE = env.MINIO_PUBLIC_URL_BASE;
